# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: www.abeclark.com
email: your-email@domain.com
description: This is the description
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abeclark.com"
twitter_username: abe_clark
github_username:  abeaclark
permalink: none

sass:
    sass_dir: _sass

navigation:
  - text: Home
    url: /
  - text: Portfolio
    title: TBU
    url: /portfolio.html
  # - text: Blog
  #   title: TBU
  #   url: /blog.html
  - text: Contact
    title: TBU
    url: /contact.html

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Build settings
markdown: redcarpet
# extensions: [fenced_code_blocks]

kramdown:
  input: GFM
  syntax_highlighter: rouge
